# Generated by Django 4.0.6 on 2022-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_category_courses_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(upload_to='portfolio'),
        ),
    ]
